# Generated by Django 4.0.5 on 2022-06-28 11:41

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 17, 11, 44, 799601)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45dd2719-8da4-496d-b9ad-2f648fd53692'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
