# Generated by Django 4.0.6 on 2022-07-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e9b4f44-f04a-455f-b722-3ea9c1831fa6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
