# Generated by Django 4.0.5 on 2022-06-28 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_created_at_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6718251-3076-4aa1-bcbb-5945e42f15db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
