# Generated by Django 4.0.6 on 2022-07-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('369c50e1-26dc-44f4-91d2-99161447fcd7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
