# Generated by Django 4.0.6 on 2022-07-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10655c6c-a7ab-4ae0-8289-9bcc53f3713d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
