# Generated by Django 4.0.5 on 2022-06-28 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b921c8e9-ed48-47e0-8dd7-b1212c1ef110'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
