# Generated by Django 4.0.5 on 2022-06-28 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fb4c872-280d-47bd-a607-f6f5f5950326'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
