# Generated by Django 4.0.6 on 2022-07-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9907a2f3-773d-4f86-8b94-68fe4187a32a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
