# Generated by Django 4.0.6 on 2022-07-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('199ef14d-2161-4fef-945a-ec9bd0670a1b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
