# Generated by Django 4.0.5 on 2022-06-28 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e4a9c90-026d-4af4-a5f8-5a8c1ae152b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
